baseURL = "https://cakedefi.com/"
googleAnalytics = ""
languageCode = "en-us"
title = "Cake"

[params]
  uen = "201918368M"
  [params.social]
    facebook = "https://facebook.com/cakedefi/"
    twitter = "https://twitter.com/cakedefi"
    reddit = "https://reddit.com/r/cakedefi/"
    youtube = "https://www.youtube.com/channel/UCkRa0RHkJ9Udd_mVWl8fa8A"
    telegram = "https://t.me/CakeDeFi_EN"

[blackfriday]

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    title = "Cake"
    description = "Grab your slice of the Decentralized Financial (DeFi) market."
    company_name = "Cake Pte. Ltd."
    copyright = "All Rights Reserved"
    weight = 3